boostcampwm-2021/iOS09-BBus

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus.xcodeproj/xcshareddata/xcschemes/BBus.xcscheme, BBus/BBus/Coordinator/AppCoordinator.swift, BBus/BBus/Coordinator/Coordinator.swift, BBus/BBus/Coordinator/SearchBusPushable.swift, BBus/BBus/Home/HomeCoornicator.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Home/Model/HomeModel.swift, BBus/BBus/Home/UseCase/HomeUseCase.swift, BBus/BBus/Home/View/HomeView.swift, BBus/BBus/Home/ViewModel/HomeViewModel.swift, BBus/BBus/SceneDelegate.swift, BBus/BBus/SearchBus/SearchBusCoordinator.swift, BBus/BBus/SearchBus/SearchBusViewController.swift
=> [뷰] 1-0. MVVM-C 패턴을 적용한 통일된 구조를 결정하여야 한다.

BBus/BBus/BusRoute/BusRouteCoordinator.swift, BBus/BBus/BusRoute/BusRouteViewController.swift
=> [뷰] 1-5. 노선도 화면이 제공되어야 한다.

BBus/BBus/Global/Network/Fetcher/GetRouteListFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetStationListFetcher.swift, BBus/BBus/Global/Network/Persistent.swift, BBus/BBus/Search/SearchCoordinator.swift, BBus/BBus/Search/SearchViewController.swift, BBus/BBus/Search/UseCase/SearchUseCase.swift
=> [검색] 2-2. 검색어를 가지고 대응되는 버스 노선 id 목록을 얻어올 수 있어야 한다. 

BBus/BBus/Global/Network/Fetcher/GetRouteListFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetStationListFetcher.swift, BBus/BBus/Global/Network/Persistent.swift, BBus/BBus/Search/SearchCoordinator.swift, BBus/BBus/Search/SearchViewController.swift, BBus/BBus/Search/UseCase/SearchUseCase.swift, BBus/BBus/Search/View/SearchNavigationView.swift, BBus/BBus/Search/View/SearchView.swift, BBus/BBus/Search/ViewModel/SearchViewModel.swift
=> [검색] 2-3. 얻어온 버스 노선 id를 바탕으로 셀 형식으로 보여줄 수 있어야 한다.

BBus/BBus/Assets.xcassets/Color/bbusTypeGreen.colorset/Contents.json, BBus/BBus/Global/Constant/BBusColor.swift, BBus/BBus/Global/Network/Fetcher/GetRouteListFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetStationListFetcher.swift, BBus/BBus/Global/Network/Persistent.swift, BBus/BBus/Search/SearchCoordinator.swift, BBus/BBus/Search/SearchViewController.swift, BBus/BBus/Search/UseCase/SearchUseCase.swift, BBus/BBus/Search/View/SearchNavigationView.swift, BBus/BBus/Search/View/SearchResultCollectionViewCell.swift, BBus/BBus/Search/View/SearchResultScrollView.swift, BBus/BBus/Search/View/SearchView.swift, BBus/BBus/Search/ViewModel/SearchViewModel.swift
=> [검색] 2-6. 얻어온 버스 노선의 종류를 표시하고, 종류에 따라 다른 색으로 표시되어야 한다.

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/BusRoute/BusRouteCoordinator.swift, BBus/BBus/BusRoute/BusRouteViewController.swift, BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/Global/Coordinator/Coordinator.swift, BBus/BBus/Global/Coordinator/Pushables.swift, BBus/BBus/Global/Extension/StringExtension.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Search/Model/SearchModel.swift, BBus/BBus/Search/Model/StationSearchResult.swift, BBus/BBus/Search/SearchViewController.swift, BBus/BBus/Search/UseCase/SearchUseCase.swift, BBus/BBus/Search/View/SearchResultCollectionViewCell.swift, BBus/BBus/Search/ViewModel/SearchViewModel.swift, BBus/BBus/Station/StationCoodinator.swift, BBus/BBus/Station/StationViewController.swift
https://user-images.githubusercontent.com/70833900/141299512-b19350aa-bafc-41d9-a476-d23d9e12f4f7.mov
없음.
=> [검색] 3-4. 셀을 터치하면 정거장 화면으로 이동해야 한다.

BBus/BBus/BusRoute/BusRouteCoordinator.swift, BBus/BBus/BusRoute/BusRouteViewController.swift, BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift
- `routeType` 값에 따라 header 의 배경색을 설정하였다.
- Combine 에서 $header 를 통해 변화를 인지할 수는 있으나, 어떻게 값을 직접받는지는 모르기에
- 현재로서는 이러한 형태로 구현된 상태이다..
```Swift
private func bindingBusRouteHeaderResult() {
self.viewModel?.$header
.receive(on: BusRouteUsecase.thread)
.sink(receiveValue: { _ in
guard let header = self.viewModel?.header else { return }
DispatchQueue.main.async {
self.busRouteView.configureHeaderView(busType: header.routeType.rawValue+"버스",
busNumber: header.busRouteName,
fromStation: header.startStation,
toStation: header.endStation)
}
})
.store(in: &cancellables)
}
```
=> [버스 노선도 정보] 7-2. 상단 헤더에 버스 종류, 버스 번호, 종착역 정보가 표시된다.

BBus/BBus/Global/Network/BBusAPIUsecases.swift, BBus/BBus/Global/Network/Fetcher/CreateFavoriteItemFetcher.swift, BBus/BBus/Global/Network/Fetcher/DeleteFavoriteItemFetchable.swift, BBus/BBus/Global/Network/Fetcher/GetArrInfoByRouteListFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetBusPosByRtidFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetFavoriteItemListFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetRouteInfoItemFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetRouteListFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetStationByUidItemFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetStationListFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetStationsByPosListFetcher.swift, BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift, BBus/BBus/Global/Network/Persistent.swift, BBus/BBus/Global/Network/Service.swift, BBus/BBus/Search/SearchCoordinator.swift
=> #72 비동기 관련 문제 스레드 동기화 하여 적용

BBus/BBus/Global/DTO/StationByUidItemDTO.swift, BBus/BBus/Global/Network/Persistent.swift, BBus/BBus/Station/StationCoodinator.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/UseCase/StationUseCase.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [정거장 정보] 4-1. 상단 헤더에 버스 ID, 정거장명, 정거장 방향이 표시된다.

BBus/BBus/BusRoute/BusRouteViewController.swift, BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/BusRoute/View/BusRouteTableViewCell.swift, BBus/BBus/BusRoute/View/BusRouteView.swift, BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Global/DTO/StationByRouteListDTO.swift, BBus/BBus/Global/Network/BBusAPIUsecases.swift, BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift
- coordinator 에서 주입된 `busRouteId` 값을 통해 API에서 받은 정보가 binding 되어있는 cell의 정보에 보여지는 구조
- BusRouteViewController 에 진입시 자동으로 보이게 된다.
- 지수님의 코드를 참고하여 이전 스타일의 컴바일을 고쳤습니다..!
- 또한 viewModel 에서 bind 가 된 후 usecase 에서 api를 부르는 순으로 수정하였습니다!
=> [버스 노선도 정보] 7-4. 셀에는 정거장 명, 정거장 번호, 첫차~종착 시간이 표시된다.

BBus/BBus/BusRoute/BusRouteViewController.swift, BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/BusRoute/View/BusRouteTableViewCell.swift, BBus/BBus/BusRoute/View/BusRouteView.swift, BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Global/DTO/StationByRouteListDTO.swift, BBus/BBus/Global/Network/BBusAPIUsecases.swift, BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift
<image src="https://user-images.githubusercontent.com/65349445/141464748-e91c89d3-cad8-4831-b9a4-620ccebbec64.gif" width=700>
- DTO 내의 transYn 값에따라 cell.configure 의 `type: stationItem.transYn != "Y" ? .waypoint : .uturn)` 값이 달라진다
- BusRouteViewController 초기 띄울시 cell 정보에 따라 자동으로 표시된다
=> [버스 노선도 정보] 7-3. 회차지는 셀 배경이 흰 색으로 표시되며, 노선도에 회차 표기를 한다.

BBus/BBus/Assets.xcassets/Color/bbusCongestionGood.colorset/Contents.json, BBus/BBus/Assets.xcassets/Color/bbusCongestionHigh.colorset/Contents.json, BBus/BBus/Assets.xcassets/Color/bbusCongestionNormal.colorset/Contents.json, BBus/BBus/BusRoute/BusRouteViewController.swift, BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/BusRoute/View/BusRouteTableViewCell.swift, BBus/BBus/BusRoute/View/BusRouteView.swift, BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Global/Constant/BBusColor.swift, BBus/BBus/Global/DTO/StationByRouteListDTO.swift, BBus/BBus/Global/Network/BBusAPIUsecases.swift, BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift
- DTO 내의 sectSpd 값에 따른 세가지 노선도 색을 설정
- 위아래 두 셀의 혼잡도가 이어지기 위해 현재, 이후 혼잡도를 통한 컬러설정로직을 구현
- BusRouteViewController 실행시 자동으로 DTO 값에 따라 Cell에 표시된다
- 위아래 두 셀의 혼잡도가 이어지기 위해서는 Cell 기준으로 현재 혼잡도와 다음 혼잡도 정보가 필요하였다.
- 하지만 여기서 첫번째, 마지막의 경우는 분기처리가 필요하였다.
- 따라서 Cell 에 configure로 넘기는 파라미터에 `speed, afterSpeed, index, count` 값을 넘겼다
- 첫번째 셀의 경우는 index == 0 으로 분기처리
- 마지막 셀의 경우는 afterSpeed == nil 로 분기처리 하여
- 그 외의 셀의 경우 speed, afterSpeed 값에 따라 노선도 색이 결정되도록 구현하였다.
```Swift
func configureLineColors(speed: Int, afterSpeed: Int?, index: Int, count: Int) -> (beforeColor:  UIColor?, afterColor:  UIColor?) {
var beforeColor: UIColor?
var afterColor: UIColor?
if afterSpeed == nil {
beforeColor = self.configureLineColor(speed: speed)
afterColor = BBusColor.clear
}
else {
guard let afterSpeed = afterSpeed else { return …
```
=> [버스 노선도 정보] 7-5. 셀 좌측의 노선도에는 현재 교통 혼잡도가 색상(빨/노/초)으로 표시되어야 한다.

BBus/BBus/Home/View/BusCellTrailingView.swift, BBus/BBus/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Home/View/RemainCongestionBadgeLabel.swift, BBus/BBus/Station/StationCoodinator.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/UseCase/StationUseCase.swift, BBus/BBus/Station/View/StationBodyCollectionViewCell.swift, BBus/BBus/Station/View/StationHeaderView.swift, BBus/BBus/Station/View/StationView.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [정거장 정보] 4-3. 버스 목록에서 도착정보가 하나도 없는 버스는 가장 아래쪽에 보여져야 한다.

BBus/BBus/Home/View/BusCellTrailingView.swift, BBus/BBus/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Home/View/RemainCongestionBadgeLabel.swift, BBus/BBus/Station/StationCoodinator.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/UseCase/StationUseCase.swift, BBus/BBus/Station/View/StationBodyCollectionViewCell.swift, BBus/BBus/Station/View/StationHeaderView.swift, BBus/BBus/Station/View/StationView.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [정거장 정보] 4-7. 셀을 누르면 해당 버스의 노선도 화면으로 이동한다.

BBus/BBus/Global/DTO/StationByUidItemDTO.swift, BBus/BBus/Home/View/BusCellTrailingView.swift, BBus/BBus/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Home/View/RemainCongestionBadgeLabel.swift, BBus/BBus/Station/StationCoodinator.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/UseCase/StationUseCase.swift, BBus/BBus/Station/View/StationBodyCollectionViewCell.swift, BBus/BBus/Station/View/StationHeaderView.swift, BBus/BBus/Station/View/StationView.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [정거장 정보] 4-6. 셀의 즐겨찾기 버튼을 통해 즐겨찾는 정류장+버스로 등록할 수 있어야 한다.

BBus/BBus/Global/DTO/StationByUidItemDTO.swift, BBus/BBus/Home/View/BusCellTrailingView.swift, BBus/BBus/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Home/View/RemainCongestionBadgeLabel.swift, BBus/BBus/Station/StationCoodinator.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/UseCase/StationUseCase.swift, BBus/BBus/Station/View/StationBodyCollectionViewCell.swift, BBus/BBus/Station/View/StationHeaderView.swift, BBus/BBus/Station/View/StationView.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [정거장 정보] 6-1. 새로고침 버튼을 누르면 자동 갱신과 별도로 데이터를 새로 받아온다.

BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/Global/Coordinator/Coordinator.swift, BBus/BBus/Global/Coordinator/Pushables.swift, BBus/BBus/Global/DTO/StationByUidItemDTO.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Home/View/BusCellTrailingView.swift, BBus/BBus/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Home/View/RemainCongestionBadgeLabel.swift, BBus/BBus/Station/StationCoodinator.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/UseCase/StationUseCase.swift, BBus/BBus/Station/View/StationBodyCollectionViewCell.swift, BBus/BBus/Station/View/StationHeaderView.swift, BBus/BBus/Station/View/StationView.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [정거장 정보] 5-1. 셀의 알람 버튼을 통해 승하차 알람 화면으로 넘어갈 수 있다.

BBus/BBus/BusRoute/BusRouteViewController.swift
- `self.viewModel?.refreshBusPos()` 를 통해 버스 위치를 업데이트 한다
=> [버스 노선도 정보] 8-1. 새로고침 버튼을 누르면 자동 갱신과 별도로 데이터를 새로 받아온다.

BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/MovingStatus/MovingStatusViewController.swift, BBus/BBus/MovingStatus/UseCase/MovingStatusUseCase.swift, BBus/BBus/MovingStatus/View/MovingStatusView.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
| Case 1 | Case 2 | Case 3 |
| -------- | -------- | -------- |
| <img src="https://i.imgur.com/SyO5Fkp.png"> | <img src="https://i.imgur.com/VRV70ad.png"> | <img src="https://i.imgur.com/HspXtzE.png"> |
- AppCoordinator 에서 넣어준 `busRouteId` 값을 통해 Persistent 에서 버스정보를 가져온다.
- 가져온 버스번호, type 에 따라 header 에 버스번호와 노선 컬러를 설정한다.
- 추후에 API를 통해 현재위치, 남은 시간이 주어질 경우 `configureHeaderInfo(currentStation: String? = nil, remainTime: Int?)` 메소드를 통해 표시할 수 있는 구조를 만들었다.
=> [승하차 알람] 11-5. 상단에는 버스 종류에 해당하는 색상으로 버스 번호를 표시하고, 그 아래에는 몇 정거장이 남았는지와 소요 예정 시간을 표시한다.

BBus/BBus/Search/UseCase/SearchUseCase.swift
=> [버그 FIX] 검색 결과가 나오지 않는 버그 해결

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Home/View/BusCellTrailingView.swift, BBus/BBus/Station/Model/BusCongestion.swift, BBus/BBus/Station/Model/BusRemainTime.swift, BBus/BBus/Station/Model/StationModel.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/View/StationView.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [리뷰 반영] #97 리뷰 반영 및 CollectionView height 수정

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Home/View/BusCellTrailingView.swift, BBus/BBus/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Station/Model/BusCongestion.swift, BBus/BBus/Station/Model/BusRemainTime.swift, BBus/BBus/Station/Model/StationModel.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/View/StationBodyCollectionViewCell.swift, BBus/BBus/Station/View/StationView.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [리뷰 반영] 정거장 정보 관련 리뷰 코드 반영

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift, BBus/BBus/AlarmSetting/UseCase/AlarmSettingUseCase.swift, BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Home/View/BusCellTrailingView.swift, BBus/BBus/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Station/Model/BusCongestion.swift, BBus/BBus/Station/Model/BusRemainTime.swift, BBus/BBus/Station/Model/StationModel.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/View/StationBodyCollectionViewCell.swift, BBus/BBus/Station/View/StationView.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [리뷰 반영] 알람 설정 관련 리뷰 코드 반영1

BBus/BBus/Global/DTO/ArrInfoByRouteDTO.swift, BBus/BBus/Global/DTO/BBusXMLDTO.swift, BBus/BBus/Global/DTO/BusPosByRtidDTO.swift, BBus/BBus/Global/DTO/StationByRouteListDTO.swift, BBus/BBus/Global/DTO/StationByUidItemDTO.swift, BBus/BBus/Global/DTO/StationsByPosDTO.swift, BBus/BBus/Global/XMLParser/BBusXMLParser.swift
=> [리뷰 반영] XML Parser 리뷰 코드 반영

BBus/BBus/Search/SearchCoordinator.swift, BBus/BBus/Search/SearchViewController.swift, BBus/BBus/Search/UseCase/SearchUseCase.swift, BBus/BBus/Search/ViewModel/SearchViewModel.swift
=> [리뷰 반영] 정거장 검색 리뷰 코드 반영

BBus/BBus/Search/SearchCoordinator.swift, BBus/BBus/Search/SearchViewController.swift, BBus/BBus/Search/UseCase/SearchUseCase.swift, BBus/BBus/Search/View/KeyboardAccessoryView.swift, BBus/BBus/Search/View/SearchNavigationView.swift, BBus/BBus/Search/View/SearchResultCollectionViewCell.swift, BBus/BBus/Search/View/SearchResultScrollView.swift, BBus/BBus/Search/View/SearchView.swift, BBus/BBus/Search/View/SimpleCollectionHeaderView.swift, BBus/BBus/Search/ViewModel/SearchViewModel.swift
- #48 #49 #50 #55 #73 #76 #77 #88 관련 final 처리 완료
=> [리뷰 반영] final 처리 - 검색 화면

BBus/BBus/Global/Constant/BBusRouteType.swift, BBus/BBus/Global/DTO/ArrInfoByRouteDTO.swift, BBus/BBus/Global/Network/Service.swift, BBus/BBus/Home/HomeCoordinator.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Home/Model/HomeModel.swift, BBus/BBus/Home/UseCase/HomeUseCase.swift, BBus/BBus/Home/View/FavoriteCollectionHeaderView.swift, BBus/BBus/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Home/ViewModel/HomeViewModel.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/View/StationBodyCollectionViewCell.swift
=> [즐겨찾기] 14-5. 셀에는 해당 정거장의 버스 도착 정보를 표시한다.

BBus/BBus/Search/View/SearchResultCollectionViewCell.swift
=> [리뷰 반영] 검색화면 버스 색상 조정

BBus/BBus/Global/DTO/BusPosByRtidDTO.swift, BBus/BBus/Global/DTO/StationByRouteListDTO.swift, BBus/BBus/Global/Network/Service.swift, BBus/BBus/MovingStatus/MovingStatusViewController.swift, BBus/BBus/MovingStatus/UseCase/MovingStatusUseCase.swift, BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift, BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift, BBus/BBus/MovingStatus/View/MovingStatusView.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
=> [승하차 알람] 11-1. 노선에 현재 유저의 위치를 표시한다.

BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
- 노선정보가 수신되면 viewController 에서 reload 가 된다.
- cell.configure 할 때 정거장의 speed 값을 넘긴다
```Swift
cell.configure(speed: stationInfo.speed,
afterSpeed: stationInfo.afterSpeed,
index: indexPath.row,
count: stationInfo.count,
title: stationInfo.title)
```
- speed, afterSpeed 값에 따라 위, 아래의 노선 색이 결정된다.
```Swift
func configureLineColors(speed: Int, afterSpeed: Int?, index: Int, count: Int) -> (beforeColor:  UIColor?, afterColor:  UIColor?) {
var beforeColor: UIColor?
var afterColor: UIColor?
if afterSpeed == nil {
beforeColor = self.configureLineColor(speed: speed)
afterColor = BBusColor.clear
}
else {
guard let afterSpeed = afterSpeed else { return (nil, nil)}
if index == 0 {
beforeColor = BBusColor.clear
afterColor = self.configureLineColor(speed: afterSpeed)
} else {
beforeColor = …
```
=> [승하차 알람] 11-2. 노선도에는 구간 단위로 현재 교통 혼잡도가 색상(빨/노/초)으로 표시되어야 한다.

BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/Global/DTO/BusPosByRtidDTO.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
1. header 정보가 persistent 로부터 수신 -> [1] `@busInfo` 설정
2. stations 정보가 api 로부터 수신 -> [2] startOrd 설정, [3] `@stationInfos` 설정, [4] `@remainingTime` 설정
3. buses 정보가 api 로부터 수신 -> [5] `@buses` 설정
4. 현재 gps 위치를 수신
5. viewController -> viewModel.findBoardBus 로직 실행
6. 탑승된 버스를 찾은 경우
6. [6] `@remainingStation` 설정 (남은 정거장수 업데이트)
7. [7] `@remainingTime` 설정 (남은 시간 업데이트)
8. [8] `@boardedBus 설정` (탑승한 버스 업데이트)
- 특정 구간 내에 속하는 특정 버스를 전체 버스 중에서 찾기가 어려워 실제 테스트를 실행해보지는 못한 상태..
- 특정 버스를 찾을 수 있다는 가정 하에 위 로직의 순서대로 `@Published` 변수값이 변경되면 ViewController 에서 화면이 업데이트 되는 구조이다.
1. 현재 탑승한 버스의 ord 값을 통해 가장 최근에 지나친 정거장의 index 값을 구한다.
2. 현재 정거장을 포함하여 이후의 정거장들의 각 sectTime 을 합하여 totalRemainTime 값을 구한다
3. 현재 버스의 위치값을 구한다 (CGFloat 값 (2.7 : 2~3 정거장 사이의 0.7만큼 움직인 거리))
4. 현재 버스의 위치값의 소수점을 구한다
5. 소수점 * 해당 정거장의 sectTime 을 곱한 후 …
=> [승하차 알람] 11-3. 버스에 탑승했을 시 몇 정거장이 남았는지 아이콘 좌측에 표시되어야 한다.

BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Home/View/HomeView.swift
https://user-images.githubusercontent.com/72058473/142147741-6eec0489-520e-4e7e-a81c-ad819a1e59bc.mp4
* 기존에 만들어져있던 favoriteReload를 활용
=> [즐겨찾기] 14-7. 새로고침시 버스 도착 정보를 갱신한다.

BBus/BBus/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift, BBus/BBus/Global/Extension/NotificationNameExtension.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Home/View/HomeView.swift, BBus/BBus/Home/ViewModel/HomeViewModel.swift, BBus/BBus/SceneDelegate.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [갱신] 17-2. 자동 갱신이 필요한 모든 화면에 대해 30초 간격으로 새로 데이터를 받아와 reload 시켜준다.

BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift, BBus/BBus/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift, BBus/BBus/AlarmSetting/UseCase/AlarmSettingUseCase.swift, BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift, BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/Global/Coordinator/Coordinator.swift, BBus/BBus/Global/Coordinator/Pushables.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
- [x ] 정거장 셀에는 정거장 명 / 정거장 ID / 승차 지점으로부터의 소요 시간이 표시되어야 한다.
=> [승하차 알람] 10-1~2. 정거장 셀에는 정거장 명 / 정거장 ID / 승차 지점으로부터의 소요 시간이 표시되어야 한다.

BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift, BBus/BBus/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift, BBus/BBus/AlarmSetting/UseCase/AlarmSettingUseCase.swift, BBus/BBus/AlarmSetting/View/AlarmSettingView.swift, BBus/BBus/AlarmSetting/View/GetOffTableViewCell.swift, BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift, BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift, BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/Global/Coordinator/Coordinator.swift, BBus/BBus/Global/Coordinator/Pushables.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/MovingStatus/MovingStatusFoldUnfoldDelegate.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
=> [승하차 알람] 9-9. 버스의 색과 동일한 색으로 승차알람 번호 색을 띄운다.

BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift, BBus/BBus/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift, BBus/BBus/BusRoute/View/CustomNavigationBar.swift, BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/Global/Coordinator/Coordinator.swift, BBus/BBus/Global/Coordinator/Pushables.swift, BBus/BBus/Home/HomeViewController.swift, BBus/BBus/Station/StationViewController.swift
=> design: #186 네비게이션 바에 버스 번호와 정거장 이름 뜨도록 설정

BBus/BBus/Global/Extension/NotificationNameExtension.swift, BBus/BBus/Info.plist, BBus/BBus/MovingStatus/MovingStatusViewController.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift, BBus/BBus/SceneDelegate.swift
- 반대방향으로 가는 가까운 버스 거르기
- 구간을 사용하여 버스 filter
- 유동적으로 시작 지점을 변화시켜 구간을 좁혀나가는 방식
- 인덱스 계산 문제
- 설명할 수 없지만 잘 안됐음.
- 버스 위치 목록 실시간 정보 받아오기
- 노티를 받아 15초마다 갱신
=> [승하차 알람] 11-13. GPS를 활용하여 이동현황표시 로직 구현

BBus/BBus/Global/Network/Service.swift
=> [데모] 트래픽 초과를 방지하기 위해 API 요청 횟수를 인당 300회로 제한한다.

BBus/BBus/MovingStatus/MovingStatusViewController.swift, BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift, BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift, BBus/BBus/MovingStatus/View/MovingStatusView.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
=> [리뷰 반영] #166 11-1. 노선에 현재 유저의 위치를 표시한다.

BBus/BBus/MovingStatus/MovingStatusViewController.swift, BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift, BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift, BBus/BBus/MovingStatus/View/MovingStatusView.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
=> [리뷰 반영] #177 11-3. 버스에 탑승했을 시 몇 정거장이 남았는지 아이콘 좌측에 표시되어야 한다.

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Global/Constant/BBusImage.swift, BBus/BBus/Global/View/CustomNavigationBar.swift, BBus/BBus/MovingStatus/MovingStatusViewController.swift, BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift, BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift, BBus/BBus/MovingStatus/View/MovingStatusView.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
=> [앵프라맹스] NavigationBar 의 BackButton 크기 조정

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Global/Constant/BBusImage.swift, BBus/BBus/Global/Extension/UINavigationControllerExtension.swift, BBus/BBus/Global/View/CustomNavigationBar.swift, BBus/BBus/MovingStatus/MovingStatusViewController.swift, BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift, BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift, BBus/BBus/MovingStatus/View/MovingStatusView.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
[블로그링크](https://medium.com/hcleedev/swift-custom-navigationview에서-swipe-back-가능하게-하기-c3c519c59bcb)
=> [앵프라맹스] NavigationController 의 좌우 스와이프 살리기

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Global/Constant/BBusImage.swift, BBus/BBus/Global/Extension/UINavigationControllerExtension.swift, BBus/BBus/Global/View/CustomNavigationBar.swift, BBus/BBus/MovingStatus/MovingStatusViewController.swift, BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift, BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift, BBus/BBus/MovingStatus/View/MovingStatusView.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
| 이동 현황 새로고침 | 버스 노선도 30초 타이머 |
| -------- | -------- |
| <img src="https://i.imgur.com/zrcNUS7.gif"> | <img src="https://i.imgur.com/QQuYFGk.gif"> |
=> [승하차 알람] 12.1 새로고침 버튼을 누르면 자동 갱신과 별도로 데이터를 새로 받아온다.

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Global/Constant/BBusImage.swift, BBus/BBus/Global/Extension/UINavigationControllerExtension.swift, BBus/BBus/Global/View/CustomNavigationBar.swift, BBus/BBus/Info.plist, BBus/BBus/MovingStatus/MovingStatusViewController.swift, BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift, BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift, BBus/BBus/MovingStatus/View/MovingStatusView.swift, BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
=> [앵프라맹스] 상태바 항상 검은색으로 표시

BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
=> [리뷰 반영] 승차 알람 도착 정보 표시 관련 리뷰 반영

BBus/BBus/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/Global/Coordinator/Coordinator.swift, BBus/BBus/Global/Coordinator/Pushables.swift, BBus/BBus/MovingStatus/MovingStatusViewController.swift
=> [리뷰 반영] PresentAlert 관련 수정

BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift, BBus/BBus/Global/Network/Service.swift, BBus/BBus/Home/View/RemainCongestionBadgeLabel.swift, BBus/BBus/Station/StationViewController.swift, BBus/BBus/Station/ViewModel/StationViewModel.swift
정거장 화면에 아직도 여러 버그가 있는 듯 보여 일주일동안 QA 진행해서 수시로 이슈 해결이 필요할 것 같다.
close #158
=> [정거장 정보] 정거장 화면 정보 안뜸 에러

BBus/BBus/Global/Network/Persistent.swift
=> [즐겨찾기] FavoriteItemList가 무한 fetch되어 메모리 사용량이 계속 증가하는 현상

BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/Foreground/AlarmSetting/Model/AlarmSettingBusArriveInfos.swift, BBus/BBus/Foreground/Home/HomeViewController.swift
=> [리뷰 반영] 즐겨찾기 버튼 터치가 씹히는 현상 리뷰 반영

BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingUseCase.swift, BBus/BBus/Foreground/AlarmSetting/View/GetOffTableViewCell.swift, BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift, BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Foreground/Home/HomeViewController.swift, BBus/BBus/Foreground/Home/UseCase/HomeUseCase.swift, BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Foreground/Home/View/HomeNavigationView.swift, BBus/BBus/Foreground/Home/ViewModel/HomeViewModel.swift, BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift, BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusUseCase.swift, BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift, BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift, BBus/BBus/Foreground/Search/UseCase/SearchUseCase.swift, BBus/BBus/Foreground/Station/StationViewController.swift, BBus/BBus/Foreground/Station/UseCase/StationUseCase.swift, BBus/BBus/Global/View/CustomNavigationBar.swift
=> [메모리 누수] coordinator.terminate() 하여도 각 ViewController 및 하위 뷰들은 메모리에 남아있다.

BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/Foreground/Station/StationViewController.swift, BBus/BBus/Global/Extension/PublisherExtension.swift, BBus/BBus/Global/Network/Service.swift
항상 guard let 은 코드의 최상단에 있어야한다는 강박이 있었는데 리뷰 덕분에 그 강박을 깰 수 있었던 것 같다.
else {} 안에 로직이 들어가지만 않는다면 guard 를 쓰는 것이 오히려 좋을 듯 하다.
close #234
=> [리뷰 반영] #221 리뷰 반영

BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift, BBus/BBus/Background/GetOnAlarm/Model/GetOnAlarmStatus.swift, BBus/BBus/Background/GetOnAlarm/UseCase/GetOnAlarmUsecase.swift, BBus/BBus/Background/GetOnAlarm/ViewModel/GetOnAlarmViewModel.swift, BBus/BBus/GetOnAlarmDelegate.swift, BBus/BBus/Global/DTO/BBusXMLDTO.swift, BBus/BBus/Global/DTO/BusPosByVehicleIdDTO.swift, BBus/BBus/Global/Extension/PublisherExtension.swift
=> [리뷰 반영] 9-11. 어느 화면에서든 승차 알람을 받을 수 있도록 하는 객체가 필요하다.

BBus/BBus/AppDelegate.swift, BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift, BBus/BBus/Background/GetOnAlarm/Model/BusApproachStatus.swift, BBus/BBus/Background/GetOnAlarm/Model/GetOnAlarmStatus.swift, BBus/BBus/Background/GetOnAlarm/UseCase/GetOnAlarmUsecase.swift, BBus/BBus/Background/GetOnAlarm/ViewModel/GetOnAlarmViewModel.swift, BBus/BBus/GetOnAlarmDelegate.swift, BBus/BBus/Global/DTO/BBusXMLDTO.swift, BBus/BBus/Global/DTO/BusPosByVehicleIdDTO.swift, BBus/BBus/Global/Extension/PublisherExtension.swift, BBus/BBus/Info.plist, BBus/BBus/SceneDelegate.swift
|foreground 푸시알림|뱃지 생성 및 초기화|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/64150179/142988125-a48fe558-b976-4330-bc45-e7333485a9b8.gif" width=400>|<img src="https://user-images.githubusercontent.com/64150179/142988580-187944f9-23c8-4efc-af37-8e679e81080c.gif" width=400>|
레퍼런스 #245 참고
- 현재 15초 주기로 네트워크 요청이 이뤄짐 5초 주기로 변경할 것인지 의논 필요
- 알람이 종료되었음이 바로 알람 설정화면에서 반영돼야함. 이 작업에 대한 논의 필요
close #245
=> [백그라운드] 15-4. 승차 알람의 경우 남은 정거장이 2정거장 이하가 될 경우 푸쉬 알림을 띄운다.

BBus/BBus/Global/Coordinator/AppCoordinator.swift
=> [앵플라맹스] 새로고침 버튼 하차 알람 설정에 따라 위치 조정

BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift, BBus/BBus/Background/GetOnAlarm/ViewModel/GetOnAlarmViewModel.swift, BBus/BBus/Global/DTO/BusPosByVehicleIdDTO.swift, BBus/BBus/Global/Extension/PublisherExtension.swift
승차 알람은 화면이 아니라 alert를 띄울 수 없어 push 알림으로 대체함
close #265
=> [네트워크] MapJSONBBusError operator 완성하기

BBus/BBus/Foreground/Station/UseCase/StationUseCase.swift
수정 후 마을버스가 사라진 모습
|수정 전|수정 후|
|:-:|:-:|
|![IMG_06888FCF4518-1](https://user-images.githubusercontent.com/70833900/143387265-94ca6374-bf51-49ea-968e-91777e1fb598.jpeg)|![Simulator Screen Shot - iPhone 12 Pro - 2021-11-25 at 14 50 36](https://user-images.githubusercontent.com/70833900/143387227-e5c5eab4-24b5-4314-8cec-733f5c294aff.png)|
- 도착 버스 목록을 받아와서 로컬에 없는 것들을 filter를 하기 위해서는 로컬 json 버스 목록 불러오기가 선행되어야 한다.
- 그런데 로컬 json 버스 목록을 불러오는 작업 또한 비동기이므로 로컬 json이 완료 되었는지 체크를 해야한다.
- combineLatest를 사용하여 서버와 로컬이 모두 받아져야 assign을 하도록 하였다.
=> [즐겨찾기] 로컬 json에 없는 버스는 홈화면에 정보가 안뜨는 버그

BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift, BBus/BBus/Background/GetOnAlarm/ViewModel/GetOnAlarmViewModel.swift
=> [리뷰 반영] 백그라운드 리뷰 & MapJSONBBusError operator 리뷰 반영

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Foreground/Home/HomeViewController.swift, BBus/BBus/Foreground/Home/View/EmptyFavoriteNoticeView.swift, BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Foreground/Home/View/HomeView.swift, BBus/BBus/Foreground/Home/View/SourceFooterView.swift, BBus/BBus/Foreground/Station/View/StationView.swift
정거장 화면 작업 중 constraint 문제랑 엮여 아직 해결 못함
정거장 화면 추가 작업 필요
=> [정거장 정보] 마지막 셀의 알람 버튼을 누를 수 없다

BBus/BBus/Foreground/BusRoute/BusRouteCoordinator.swift, BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift, BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
=> [리펙토링] BusRouteUsecase 화면 UseCase 리펙토링

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift, BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift, BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUseCase.swift, BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift, BBus/BBus/Global/Coordinator/AppCoordinator.swift
=> [리펙토링] MovingStatusUsecse 화면 UseCase 리펙토링

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Foreground/AlarmSetting/AlarmSettingCoordinator.swift, BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingCalculateUseCase.swift, BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift, BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUseCase.swift, BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusCalculateUseCase.swift, BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift, BBus/BBus/Global/Coordinator/AppCoordinator.swift, BBus/BBus/Global/UseCase/AverageSectionTimeCalculatable.swift
=> [리펙토링] MovingStatusViewModel 로직을 UseCase 로 이동

BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingAPIUseCase.swift, BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
=> [리팩토링] AlarmSettingViewModel의 useCase 타입 변경

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Foreground/Search/SearchCoordinator.swift, BBus/BBus/Foreground/Search/SearchViewController.swift, BBus/BBus/Foreground/Search/UseCase/SearchAPIUseCase.swift, BBus/BBus/Foreground/Search/UseCase/SearchCalculateUseCase.swift, BBus/BBus/Foreground/Search/ViewModel/SearchViewModel.swift
=> [리팩토링] Search 화면 UseCase 리팩토링

BBus/BBus/Foreground/Home/HomeViewController.swift, BBus/BBus/Global/Base/BaseViewController.swift
=> [리펙토링] HomeViewController: BaseViewController 채택

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Background/GetOnAlarm/UseCase/GetOnAlarmAPIUsecase.swift, BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingAPIUseCase.swift, BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/Foreground/Home/HomeCoordinator.swift, BBus/BBus/Foreground/Home/HomeViewController.swift, BBus/BBus/Foreground/Home/UseCase/HomeAPIUseCase.swift, BBus/BBus/Foreground/Home/UseCase/HomeCalculateUseCase.swift, BBus/BBus/Foreground/Home/ViewModel/HomeViewModel.swift, BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUseCase.swift, BBus/BBus/Global/Network/RequestUsecases.swift
=> [리팩토링] 홈화면 UseCase리팩토링

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Foreground/AlarmSetting/View/AlarmSettingView.swift, BBus/BBus/Foreground/BusRoute/View/BusRouteView.swift, BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift, BBus/BBus/Foreground/Station/View/StationView.swift, BBus/BBus/Info.plist
=> [버그] 가로모드 지원 제한 & 다크모드 로더 색상 변경

BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
=> [리펙토링] BusRouteViewModel, MovingStatusViewModel - UseCase -> Useable 타입으로 수정

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Background/GetOffAlarm/GetOffAlarmController.swift, BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift, BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift, BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift, BBus/BBus/Global/DeviceConfig/AlarmCenter.swift
권한 허용 상태를 지속적으로 관찰하도록 구현해야해 시간 관계 상 생략
close #277
=> [리팩토링, 버그] UserNotification을 담당하는 객체 분리 및 권한 허용되어있지 않을 시 환경설정으로 넘어가기

BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift, BBus/BBus/Foreground/AlarmSetting/View/AlarmSettingView.swift, BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift, BBus/BBus/Foreground/BusRoute/View/BusRouteView.swift, BBus/BBus/Foreground/Home/View/HomeView.swift, BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift, BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift, BBus/BBus/Foreground/Station/StationViewController.swift, BBus/BBus/Foreground/Station/View/StationView.swift, BBus/BBus/Global/CustomView/CustomNavigationBar.swift, BBus/BBus/Global/CustomView/NavigatableView.swift, BBus/BBus/Global/CustomView/RefreshButton.swift, BBus/BBus/Global/CustomView/RefreshableView.swift
=> [리팩토링] 새로고침 버튼, Navigation Bar를 각 화면의 view 내에 속하게 수정

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift, BBus/BBus/Background/GetOnAlarm/UseCase/GetOnAlarmAPIUseCase.swift, BBus/BBus/Background/GetOnAlarm/ViewModel/GetOnAlarmViewModel.swift, BBus/BBus/Foreground/BusRoute/BusRouteCoordinator.swift, BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift, BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift, BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUseCase.swift, BBus/BBus/Foreground/Search/SearchCoordinator.swift, BBus/BBus/Foreground/Search/UseCase/SearchAPIUseCase.swift, BBus/BBus/Foreground/Station/StationCoordinator.swift, BBus/BBus/Foreground/Station/UseCase/StationAPIUseCase.swift, BBus/BBus/Global/Coordinator/AppCoordinator.swift
=> [리팩토링] usecase → useCase로 통일

BBus/BBus.xcodeproj/project.pbxproj, BBus/BBus/Global/DTO/BusPosByRtidDTO.swift, BBus/BBus/Global/DTO/StationByRouteListDTO.swift, BBus/BusRouteViewModelTests/BusRouteViewModelTests.swift, BBus/RequestFactoryTests/RequestFactoryTests.swift
=> [테스트] BusRouteViewModelTests 작성

BBus/BBus/Foreground/AlarmSetting/View/AlarmSettingView.swift
=> [버그] 승차 알람 섹션 헤더가 보이지 않는 문제 해결

BBus/BBus/Foreground/AlarmSetting/View/GetOnStatusCell.swift, BBus/BBus/Foreground/BusRoute/View/BusRouteView.swift, BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift, BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift, BBus/BBus/Foreground/Search/View/SearchResultCollectionViewCell.swift, BBus/BBus/Global/Constant/BBusRouteType.swift, BBus/BBus/Global/DTO/BusRouteDTO.swift, BBus/BBus/Global/Resource/BusRouteList.json
=> feat: #345 마을버스, 다른 버스들 대응
