boostcampwm-2021/iOS09-BBus

BBus/BBus/BusRoute/BusRouteCoordinator.swift
BBus/BBus/Global/Coordinator/AppCoordinator.swift
BBus/BBus/Global/Coordinator/Coordinator.swift
BBus/BBus/Global/Coordinator/Pushables.swift
BBus/BBus/Home/HomeViewController.swift
BBus/BBus/Search/SearchViewController.swift
BBus/BBus/Station/StationViewController.swift

close #44 
화면 전환 시 버스노선 id가 출력되는 모습.
https://user-images.githubusercontent.com/70833900/141274682-ae80577c-93e3-418a-8fcd-e6c17cfed0c1.mov
- 넘겨받은 busRouteId를 coordinator에서 어떻게 처리할 것인가?
1. let busRouteId: Int 처럼 프로퍼티로 가지고 있다가 start() 할 때 사용한다.
2. AppCoordinator에서 BusRouteCooridnator.start(busRouteId: 33) 처럼 start의 인자로 넘겨준다.
- Coordinator의 역할 측면에서 busRouteId를 프로퍼티로 **저장**하고 있을 필요는 없다고 생각함.
- 넘겨받아서 다음화면에 전달을 해주기만 하면 되므로 start에서 인자로 받아 사용하고 끝내는 것이 맞다고 판단함.

[검색] 2-4. 셀을 터치하면 노선도 화면으로 이동해야 한다.

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/BusRoute/BusRouteCoordinator.swift
BBus/BBus/Global/Coordinator/AppCoordinator.swift
BBus/BBus/Global/Coordinator/Coordinator.swift
BBus/BBus/Global/Coordinator/Pushables.swift
BBus/BBus/Global/Extension/StringExtension.swift
BBus/BBus/Home/HomeViewController.swift
BBus/BBus/Search/Model/SearchModel.swift
BBus/BBus/Search/Model/StationSearchResult.swift
BBus/BBus/Search/SearchViewController.swift
BBus/BBus/Search/UseCase/SearchUseCase.swift
BBus/BBus/Search/ViewModel/SearchViewModel.swift
BBus/BBus/Station/StationViewController.swift

close #65 
망원동 검색 예시
https://user-images.githubusercontent.com/70833900/141294226-0db50be6-9ea0-4c94-98cb-c1f03b323361.mov
- 문자열 내에서 키워드를 포함하고 있는 모든 부분들을 어떻게 찾을 것인가?
- 문자열 내에서 x라는 문자열의 첫번째 등장 위치를 찾아 Range<String.Index>로 반환하는 메소드는 있음. `string.range(of:)`
- 그러나 모든 등장 위치를 찾아 Range의 배열형태 `[Range<String.Index>]`로 반환하는 메소드는 없었음.
- ->`extension String` 으로 직접 `ranges(of:) -> [Range<String.Index>]` 메소드를 구현해두었음.

[검색] 3-2. 검색어를 가지고 정거장 이름 혹은 번호에 대응되는 정거장 id를 얻어올 수 있어야 한다.

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/BusRoute/BusRouteCoordinator.swift
BBus/BBus/Global/Coordinator/AppCoordinator.swift
BBus/BBus/Global/Coordinator/Coordinator.swift
BBus/BBus/Global/Coordinator/Pushables.swift
BBus/BBus/Global/Extension/StringExtension.swift
BBus/BBus/Home/HomeViewController.swift
BBus/BBus/Search/Model/SearchModel.swift
BBus/BBus/Search/Model/StationSearchResult.swift
BBus/BBus/Search/SearchViewController.swift
BBus/BBus/Search/UseCase/SearchUseCase.swift
BBus/BBus/Search/View/SearchResultCollectionViewCell.swift
BBus/BBus/Search/ViewModel/SearchViewModel.swift
BBus/BBus/Station/StationViewController.swift

| 정거장명으로 검색 | arsID로 검색 |
|:---:|:---|
|![이름으로검색](https://user-images.githubusercontent.com/70833900/141297330-672fd329-763d-4d66-b309-d9b5711ca91d.gif) |![arsID로 검색](https://user-images.githubusercontent.com/70833900/141297362-09e5cacd-8418-4bd3-ac47-76aae0380a31.gif) |
- 버스검색과 정거장 검색의 섹션 헤더를 따로 처리해주어야 하는 이슈
- 현재 검색 모드가 '버스'인지 '정거장'인지 판별을 어떻게 해야할지 고민이었음
- 아래 cell 리턴하는 delegate 메소드에서 아래와 같이 origin으로 접근하는 로직이 있어 같은 방식으로 구현하였음.
```Swift
func numberOfSections(in collectionView: UICollectionView) -> Int {
let regionCount = 1
if collectionView.frame.origin.x == 0 {
return self.viewModel?.busSearchResults.count == 0 ? 0 : regionCount
}
else {
return self.viewModel?.stationSearchResults.count == 0 ? 0 : regionCount
}
}
```

[검색] 3-3. 얻어온 정거장 id를 바탕으로 셀 형식으로 보여줄 수 있어야 한다.

---

BBus/BBus/BusRoute/BusRouteCoordinator.swift
BBus/BBus/BusRoute/BusRouteViewController.swift
BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift
BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift

- BusRouteCoordinator 에서 넣어준 특정 `busRouteId` 값에 따라 header 내용이 바뀐다
```Swift
func start() {
let usecase = BusRouteUsecase(usecases: BBusAPIUsecases(), busRouteId: 100100071)
let viewModel = BusRouteViewModel(usecase: usecase)
let viewController = BusRouteViewController(viewModel: viewModel)
viewController.coordinator = self
self.navigationPresenter.pushViewController(viewController, animated: true)
}
```
- Combine 에서 $header 를 통해 변화를 인지할 수는 있으나, 어떻게 값을 직접받는지는 모르기에
- 현재로서는 이러한 형태로 구현된 상태이다..
```Swift
private func bindingBusRouteHeaderResult() {
self.viewModel?.$header
.receive(on: BusRouteUsecase.thread)
.sink(receiveValue: { _ in
guard let header = self.viewModel?.header else { return }
DispatchQueue.main.async {
self.busRouteView.configureHeaderView(busType: header.routeType.rawValue+"버스", …
```

[버스 노선도 정보] 7-1. 특정 버스 노선 id를 통해 xml 파일을 얻어올 수 있어야 한다

---

BBus/BBus/Assets.xcassets/Color/bbusCongestionGood.colorset/Contents.json
BBus/BBus/Assets.xcassets/Color/bbusCongestionHigh.colorset/Contents.json
BBus/BBus/Assets.xcassets/Color/bbusCongestionNormal.colorset/Contents.json
BBus/BBus/BusRoute/BusRouteViewController.swift
BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift
BBus/BBus/BusRoute/View/BusRouteTableViewCell.swift
BBus/BBus/BusRoute/View/BusRouteView.swift
BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift
BBus/BBus/Global/Constant/BBusColor.swift
BBus/BBus/Global/DTO/BusPosByRtidDTO.swift
BBus/BBus/Global/DTO/StationByRouteListDTO.swift
BBus/BBus/Global/Network/BBusAPIUsecases.swift
BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift

- BusRouteViewController 에서 binding 을 설정한다
- 버스 위치정보들이 수신되면 viewModel 에서 `BusPosInfo` 로 변환된 정보들을 ViewController 에서 수신한다
- 이전 tag 들을 모두 제거한 후 `busRouteView.createBusTag` 를 통해 태그 정보들을 넣어 생성한다
- API 내에 있는 `sectionOrder, sectDist, fullSectDist` 값을 사용하여
- `(sectOrder-1) + (sectDist/fullSectDist)` 값을 통해 각 정거장 사이의 CGFloat의 Y 값을 얻을 수 있었다.
```Swift
private func convertBusPos(order: Int, sect: String, fullSect: String) -> CGFloat {
let order = CGFloat(order-1)
let sect = CGFloat((sect as NSString).floatValue)
let fullSect = CGFloat((fullSect as NSString).floatValue)
return order + (sect/fullSect)
}
```
- BusTagView의 경우 API의 새로운 정보값에 따라 제거되고 생성되어야 하는 구조이므로 인스턴스를 지녀야하며, 제거가 가능해야 한다.
- 따라서 BusRouteViewController 내에 `private var busTags: [BusTagView] = []` 변수를 생성하여 지니게끔 구현하였다.
- API 값이 바뀌게 되면 기존 Tag 들을 …

[버스 노선도 정보] 7-7. 버스 아이콘 좌측에 말풍선 아이콘으로 해당 버스 번호판 4자리와, 혼잡도를 표시한다.

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/Search/Model/BusSearchResult.swift
BBus/BBus/Search/Model/SearchResults.swift
BBus/BBus/Search/Model/StationSearchResult.swift
BBus/BBus/Search/SearchViewController.swift
BBus/BBus/Search/UseCase/SearchUseCase.swift
BBus/BBus/Search/View/SearchResultCollectionViewCell.swift
BBus/BBus/Search/ViewModel/SearchViewModel.swift

- NSMutableAttributedText에서 특정 range에만 attribute를 먹일 때 range 타입 이슈
- string에서 특정 단어와 일치하는 모든 부분을 찾아내는 ranges(of: ) 메소드를 StringExtension 으로 구현해뒀었음.
- range(of:) 함수의 리턴 타입이 Range<String.Index>여서 ranges(of:)도 [Range<String.Index>] 타입으로 리턴하도록 구현해뒀는데
- NSMutableAttributedText에 addAttributes를 하려고 하니 range를 NSRange 타입으로 넘겨주어야 해서 타입이 일치하지 않는 이슈가 있었음.
- 다음과 같은 해결방법이 있었는데,
1. ranges(of:) 함수의 리턴타입을 [NSRange]로 변경
2. UseCase 쪽에서 ranges(of:)함수를 사용한 뒤, [NSRange] 타입으로 변환하여 저장
- NSString이 아닌 String의 Extension이기 때문에 [NSRange]으로 리턴하는 것보다는 변환해서 쓰는 것이 맞다고 생각하여 최종적으로 2번 방식으로 구현함.
- 컬렉션뷰와 뷰모델의 stationSearchResult를 바인딩하는 코드를 빼먹었는데도 잘 작동하는 이슈
- 현재 사용자가 어느 검색모드에 있든 텍스트필드의 keyword가 바뀌면 버스와 정거장 모두 재검색을 하게 됨.
- 버스와 정거장이 하나의 collectionView에 표시되어 있으므로 busSearchResult와 stationSearchResult 중 하나만 바인딩을 해도 문제가 없음.
- 오히려 두 …

[검색] 3-6. 얻어온 정거장의 이름 또는 번호와 일치하는 부분을 주황색으로 표시한다.

---

BBus/BBus/Home/HomeViewController.swift
BBus/BBus/Home/View/FavoriteCollectionHeaderView.swift
BBus/BBus/Home/View/HomeView.swift

- tapGestureRecognizer의 action 함수에서 sender의 타입은 무엇으로 해야하는가?
- 일단 맞는 타입은 `UITapGestureRecognizer`이다.
- `sender: Any`로 받아서 출력해보면 UITapGestureRecognizer 타입이다.
``` Swift
@objc private func headerViewTapped(_ sender: UITapGestureRecognizer) {
delegate?.shouldGoToStationScene(headerView: self)
}
```
- 그런데 아래와 같이 `UICollectionViewReusableView` 타입으로 받아도 문제가 없다.???
``` Swift
@objc private func headerViewTapped(_ sender: UICollectionViewReusableView) {
delegate?.shouldGoToStationScene(headerView: self)
}
```
- 그래서 String 같이 전혀 관계없는 타입으로도 시도해보았다. 그 결과 `sender: String`으로 받는 것은 안된다.
- 그래서 나온 추측:  action을 실행할 때 UITapGestureRecognizer를 AnyObject나 NSObject 같은 상위 타입으로 캐스팅해서 파라미터에 전달한다.
-> 이 추측이 맞다면 print나 dump 했을 때 구체타입으로 출력이 안될텐데 되는 것을 보면 이건 아니다.
** 해결 못함 **
Close #141

[즐겨찾기] 14-3. 헤더를 누르면 알맞는 정거장 화면으로 이동한다.

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/AlarmSetting/View/AlarmSettingView.swift
BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
BBus/BBus/AlarmSetting/View/NoneInfoTableViewCell.swift
BBus/BBus/Global/Constant/BBusImage.swift
BBus/BBus/Global/Network/AccessKey.xcconfig
BBus/BBus/Global/Network/Service.swift

1. 도착 정보가 두개 온 경우 
2. 도착 정보가 하나 온 경우
3. 도착 정보가 안 온 경우
를 순서대로 보여주고 있음
처음에는 GetOnStatusCell에 아래 버튼, 라벨을 표시시켜 isHidden으로 처리해주었으나
GetOnStatusCell에 해당 로직이 있으면 GetOnStatusCell 내부 isHidden 로직이 복잡해져 아무 정보도 없을 경우 뜨는 TableViewCell은 NoneInfoTableViewCell로 완전히 분리시켜 주었습니다.
그러고나니 로직이 보다 깔끔해졌습니다. 
close #105

[승하차 알람] 9-2. 도착정보가 없으면 표시하지 않고, 남은 시간은 API가 보낸 메세지를 그대로 띄운다.2

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift
BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
BBus/BBus/Global/Extension/NotificationNameExtension.swift
BBus/BBus/Global/Network/Service.swift
BBus/BBus/Home/HomeViewController.swift
BBus/BBus/Home/Model/HomeModel.swift
BBus/BBus/Home/ViewModel/HomeViewModel.swift
BBus/BBus/SceneDelegate.swift
BBus/BBus/Station/Model/BusRemainTime.swift
BBus/BBus/Station/StationViewController.swift
BBus/BBus/Station/ViewModel/StationViewModel.swift

|홈 화면|알람 설정 화면|정거장 화면|
|:---:|:---:|:---:|
|![](https://i.imgur.com/xIQkCeX.gif)|![](https://i.imgur.com/Ym98Phj.gif)|![](https://i.imgur.com/ezFeDvI.gif)|
* SceneDelegate에서 Timer를 fire해줌.
* 1초 타이머를 작동시켜, 타이머가 필요한 각 화면에서 그 액션을 받아서 사용하기로 결정
* 만약 각 화면에서 타이머를 독립적으로 작동시킨다면, 화면이 계속 push 됨에 따라 타이머가 오작동하거나 메모리상에서 해제되지 않은 채 남을 수 있다.
* 기존에는 아래와 같이 Timer를 작동시켰음.
```swift
Timer.init(timeInterval: 1, repeats: true) {
NotificationCenter.default.post(name: .oneSecondPassed, object: nil)
}
```
* 서치 결과 타이머는 main run loop에서 돌리는 것이 가장 안정하다고 함. (run loop 관련 지식은 이슈 #123 참고)
* 하지만 main run loop는 뷰 관련 입력 이벤트가 처리되는 런루프로 타이머와 뷰 이벤트를 모두 처리하기에 버거울 수 있다.
* run loop mode를 common으로 하면 main에서 이루어지는 view 관련 이벤트의 영향을 덜 받도록 할 수 있음.
* default 모드에서는 스크롤 시 타이머가 멈추는 증상이 있었지만 common으로 변경 후에는 해결됨.
```swift
let timer = …
```

[갱신] 17-1. 남은 정류소 시간을 보여주는 모든 화면에 대해 1초 간격으로 줄어드는 뷰를 보여준다.

---

BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/AlarmSetting/View/AlarmSettingView.swift

#167  참고
* 알람설정 화면에서 하차알람을 설정한다.
https://user-images.githubusercontent.com/72058473/142147328-f390d2fa-6668-46fc-a7fe-e9902820f2d0.mp4
* Section만 업데이트 해주는 방식으로 변경

fix: #167 승차 알람 섹션만 매 초마다 갱신하는 방식으로 변경

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
BBus/BBus/Global/Extension/NotificationNameExtension.swift
BBus/BBus/Global/View/ThrottleButton.swift
BBus/BBus/Home/HomeViewController.swift
BBus/BBus/Home/View/HomeView.swift
BBus/BBus/Home/ViewModel/HomeViewModel.swift
BBus/BBus/SceneDelegate.swift
BBus/BBus/Station/StationViewController.swift
BBus/BBus/Station/ViewModel/StationViewModel.swift

새로고침 버튼을 연타해도 3초에 한 번 씩만 refresh()가 호출됨.
* 새로고침을 연타하는경우 API 요청이 너무 많아져서 토큰이 소진될 우려가 있다.
* 따라서 일정 시간동안 모든 요청을 하나로 바꿔주는 throttle 기술을 적용한 버튼이 필요

[새로고침 버튼] 모든 새로고침 버튼에 throttle 할 수 있게 커스텀하여 만들어준다. 

---

BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift
BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/AlarmSetting/View/AlarmSettingView.swift
BBus/BBus/AlarmSetting/View/GetOffTableViewCell.swift
BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
BBus/BBus/Global/Coordinator/AppCoordinator.swift
BBus/BBus/MovingStatus/MovingStatusFoldUnfoldDelegate.swift

[승하차 알람] 10-3. 정거장 셀의 알람 버튼을 터치하면 실시간 이동 현황 화면으로 전환되어야 한다. 

---

BBus/BBus/MovingStatus/MovingStatusViewController.swift
BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift
BBus/BBus/MovingStatus/View/MovingStatusView.swift

| Case 1 | Case 2 |
| -------- | -------- |
| <img src="https://i.imgur.com/l3z0OsP.jpg"> | <img src="https://i.imgur.com/6ZCTIhS.jpg"> |
| 1정거장 로직 1 | 1정거장 로직 2 |
| <img src="https://i.imgur.com/y5OQ0In.jpg"> | <img src="https://i.imgur.com/lfwF3qy.jpg"> |
- viewModel 의 남은 정거장 수에 따라 말풍선에 표시가 된다.
- `self.viewModel?.$remainingStation` 값을 바인딩 하고 있어 `self?.movingStatusView.configureHeaderInfo(remainStation: currentStation, remainTime: self?.viewModel?.remainingTime)` 가 실행되는 구조
- 현재로선  `self.viewModel?.$remainingStation` 값이 바뀔 수 없기에 임의로 값을 대입하여 테스트

[승하차 알람] 11-4. 1정거장 전부터는 "이번에 내리세요" 라는 메세지가 말풍선 아이콘에 표시되어야 한다.

---

BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
BBus/BBus/Global/Coordinator/AppCoordinator.swift
BBus/BBus/Global/Coordinator/Coordinator.swift
BBus/BBus/Global/Coordinator/Pushables.swift

1번째, 0번째 전 정거장이거나, 곧도착일 시 승차알람 설정이 되지 않음

[승하차 알람] 9-7. 1번째 전 정거장에 버스가 위치할 경우 알람 등록이 되지 않으며 "버스가 곧 도착합니다"라는 메시지를 띄운다.

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/BusRoute/BusRouteViewController.swift
BBus/BBus/Global/Coordinator/AppCoordinator.swift
BBus/BBus/Global/Coordinator/Coordinator.swift
BBus/BBus/Global/Coordinator/Pushables.swift
BBus/BBus/Home/HomeViewController.swift
BBus/BBus/Info.plist
BBus/BBus/MovingStatus/MovingStatusViewController.swift
BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
BBus/BBus/Search/SearchViewController.swift
BBus/BBus/Station/StationViewController.swift

- Background 에서 gps 를 fetch 할 수 있도록 project 및 info.plist 를 설정
- Background 가 살아있기에 15초 간 API를 fetch 할 수 있음
- 탑승된 boardedBus 가 판별되면 남은 정거장수를 업데이트 하는 `updateRemainingStation` 메소드가 실행
- 이후 remainingStation 값에 따라 push 로직을 처리하도록 구현
- 만약 하차 정거장에 도착하였을 경우 API 요청을 못하도록 처리
- ViewController 에서 또한 Alert를 띄우도록 처리
- 다시 화면에 돌아왔을 시 확인 버튼을 클릭하면 자동으로 MovinigStatusViewController 가 닫히도록 로직 작성
```Swift
// 남은 정거장 수 업데이트 로직
private func updateRemainingStation(bus: BusPosByRtidDTO) {
guard let startOrd = self.startOrd else { return }
let remainStation = (self.stationInfos.count - 1) - (bus.sectionOrder - startOrd) // 6
if self.remainingStation != remainStation {
self.pushAlarm(remainStation: remainStation)
self.remainingStation = remainStation
}
}
```
```Swift
// 정거장 수가 변화되었을 경우 알람 푸쉬 로직
private func …
```

[승하차 알람] 11-6. 하차 정거장에 도착할 경우 "알람이 종료됩니다"라는 Alert 메세지를 띄우고 알람이 자동 종료된다.

---

BBus/BBus/BusRoute/BusRouteViewController.swift
BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift
BBus/BBus/Station/StationViewController.swift
BBus/BBus/Station/UseCase/StationUseCase.swift

- 구현 방식
- 일단 노선도화면/정거장화면으로 진입한 뒤, 로컬 json에서 id로 filter한 결과가 nil일 경우 alert를 띄우고, coordinator.terminate 하게 함.
- 모든 버스와 정거장에서 alert가 뜨는 문제 
- @Published 프로퍼티를 쓸 경우 최초 init된 값인 nil이 한번 publish되기 때문에 모든 버스와 정거장에서 alert이 뜨는 문제가 있었음.
- `dropFirst()`로 이후 값만 리시브하도록 함.

[정거장 정보] 마을버스 클릭시 앱이 죽는 현상

---

BBus/BBus/Foreground/Station/StationViewController.swift

- 별모양 버튼 터치 시 favoriteItems가 변경됨
- favoriteItems가 변경되면 reload 되도록 바인딩이 걸려있음.
- reload 대신 버튼 색상만 다시 configure 하도록 바인딩하여 reload 때문에 깜빡이는 현상을 해결함.
- 그런데 문제는 최초로 favoriteItems를 불러왔을 때는 reload를 해야된다는 점.
- 아래와 같이 최초로 receive 했을 때만 reload 하도록 `first()` 오퍼레이터를 걸어줌.
``` swift
self.viewModel?.$favoriteItems
.receive(on: StationUsecase.queue)
.compactMap { $0 }
.first()
.sink(receiveValue: { [weak self] _ in
DispatchQueue.main.async {
self?.stationView.reload()
}
})
.store(in: &self.cancellables)  
```

[정거장 정보] 즐겨찾기 추가/해제 시 화면이 깜빡이는 현상

---

BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift
BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
BBus/BBus/Global/Coordinator/AppCoordinator.swift
BBus/BBus/Global/Coordinator/Coordinator.swift
BBus/BBus/Info.plist

- fold, unfold 상태에 따른 alert 로직 에러 확인하여 로직을 추가하였음
| unfold 상태 | fold 상태 |
| -------- | -------- |
| <img src="https://i.imgur.com/QL5EJOT.gif"> |<img src="https://i.imgur.com/wWmnpwW.gif"> |
- viewModel 내에 `private(set) var isFolded: Bool = false` 변수를 추가
- 접히고 필때마다 값 변경
- 종료 alert 로직에서 변수 값에 따른 분기처리 추가
```Swift
guard let isFolded = self.viewModel?.isFolded else { return }
if isFolded {
self.coordinator?.presentAlertToNavigation(controller: controller, completion: nil)
}
else {
self.coordinator?.presentAlertToMovingStatus(controller: controller, completion: nil)
}
```

[리뷰 반영] #227 11-6. 하차 정거장에 도착할 경우 "알람이 종료됩니다"라는 Alert 메세지를 띄우고 알람이 자동 종료된다.

---

BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift
BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
BBus/BBus/Foreground/Home/HomeViewController.swift
BBus/BBus/Foreground/Home/ViewModel/HomeViewModel.swift
BBus/BBus/Foreground/Station/StationViewController.swift
BBus/BBus/Foreground/Station/ViewModel/StationViewModel.swift

- `NotificationCenter.default.removeObserver(self)` 메소드를 통해 Notification 에 등록된 observer 를 제거하는 식으로 누수되는 API 를 막았다.

[갱신] 무한 push로 쌓인 화면들에서도 자동갱신 때문에 api를 요청하는 문제

---

BBus/BBus/Global/Coordinator/AppCoordinator.swift

movingStatusWindow가 hidden이 아닐 경우 height를 변경하지 않도록 하여 해결
close #262

[버그] 하차알림 페이지 알람 버튼 클릭 시 화면 height관련 에러 해결

---

BBus/BBus/Foreground/Home/HomeViewController.swift

- 기존에는 2n번 reload되는 로직이어서 throttle을 걸어두었었음. -> throttle 때문에 중간에 씹혀서 2초가 한번에 깎였던 것으로 추측
- 각 셀을 개별적으로 매 초 configure하는 것으로 바꾸어 저절로 해결이 된 것 같음
- 모든 화면에 대해 2분이상 관찰하였는데 2초씩 깎이는 현상은 일어나지 않았음.
- home 화면의 경우 자동/수동 새로고침을 할 때마다 2n+2번의 reload가 일어나는 이슈가 남아있어 혹시 모를 상황을 대비해 debounce를 0.1초로 걸어두었음.

[갱신] 1초 타이머에서 2초씩 깎이는 현상

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/Background/GetOffAlarm/GetOffAlarmController.swift
BBus/BBus/Background/GetOffAlarm/Model/GetOffAlarmStatus.swift
BBus/BBus/Background/GetOffAlarm/ViewModel/GetOffAlarmViewModel.swift
BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift
BBus/BBus/Background/GetOnAlarm/Model/AlarmStartResult.swift
BBus/BBus/Foreground/AlarmSetting/AlarmSettingCoordinator.swift
BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/Foreground/AlarmSetting/Model/AlarmSettingBusArriveInfos.swift
BBus/BBus/Foreground/AlarmSetting/View/GetOffTableViewCell.swift
BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
BBus/BBus/Foreground/Home/HomeViewController.swift
BBus/BBus/Foreground/MovingStatus/MovingStatusFoldUnfoldDelegate.swift
BBus/BBus/Foreground/Search/SearchViewController.swift
BBus/BBus/Foreground/Station/StationViewController.swift
BBus/BBus/Foreground/Station/ViewModel/StationViewModel.swift
BBus/BBus/Global/Coordinator/AppCoordinator.swift

* 하차 알람 중복 체크 로직을 어떻게 짜야할까?
1. MovingStatusViewController로 판단
* coordinator를 통해 조회하는 방법 -> openMovingStatus에서 result 값으로 이미 있는지, 중복되는지, 없는지 판단해서 뿌려줌
* 하지만 이 방법은 다른 뷰들이 알람이 생성되었다는 사실을 확인하기 위해서 coordinator에 접근해야하는데, 그에대한 로직을 coordinator로 짜기엔 조금 의도가 다르게 수행될 우려가 있음.
2. GetOnAlarmController처럼 singleton으로 확인
* MovingStatusViewController가 항상 살아잇는데 그걸로 하면 되지 왜?
* 홈 화면 및 정거장 화면에서도 이걸 접근해야하기 때문이다. MovingStatus로 하게 되면 너무 깊은 관게가 되어버리고 getOff와 로직이 너무 상이해지기에 헷갈릴 우려가 있다.
* MovingStatusViewController로 확인하면 ViewModel에 바인딩 하기가 까다롭다.
* 결국 GetOffAlarmController를 하나 만들어서 싱글톤으로 관리하기로 결정

[승하차 알람] 10-4. 하차 알림이 설정되어있는 경우 알람 버튼이 빨간색으로 표시되어야 한다.

---

BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift

fix: #275 하차 알람 관련 버그 해결

---

BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingUseCase.swift

- nil -> error로 리팩토링하는 것이 어떻냐는 피드백은 현재 구조로서는 크게 필요하지 않아 반영하지 않았음.
- 현재 구조: 로컬 json에 없는 버스는 아예 정거장 화면에서 보여주지 않으므로 서울버스 인데 서울시에서 정보를 제공해주지 않는 버스에 대해서만 처리하면 됨!
- 현재 서울버스 API가 개선된 것인지 웬만한 버스(마을버스, 파주버스.. 등) 에 대해 다 하차알람 섹션 정보가 제공이 되는 것으로 확인함.

[리뷰 반영] 다른 지역 버스에 대해 승하차 알람 화면 진입시 하차 알람 섹션이 뜨지 않음

---

BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/Foreground/AlarmSetting/View/AlarmSettingView.swift
BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift
BBus/BBus/Foreground/BusRoute/View/BusRouteView.swift
BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift
BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift
BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift
BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
BBus/BBus/Foreground/Station/StationViewController.swift
BBus/BBus/Foreground/Station/View/StationView.swift
BBus/BBus/Foreground/Station/ViewModel/StationViewModel.swift

- 각 화면에서 정보가 보이기 전까지 로더가 표시된다.

[데이터 로딩] 16-1. 각 화면에서 네트워크 요청에 대해 response가 오기 전까지 로더를 보여준다

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/Foreground/Station/Model/BusArriveInfos.swift
BBus/BBus/Foreground/Station/Model/BusSectionKeys.swift
BBus/BBus/Foreground/Station/StationViewController.swift
BBus/BBus/Foreground/Station/ViewModel/StationViewModel.swift

[일급 컬렉션](https://velog.io/@tigger/%EC%9D%BC%EA%B8%89-%EC%BB%AC%EB%A0%89%EC%85%98)
[일급 컬렉션 (First Class Collection)의 소개와 써야할 이유](https://jojoldu.tistory.com/412)
리팩토링이므로 실행 방식과 동일하다
maxCount로 ViewController 에서 갯수 파악하는 로직을 제거
딕셔너리를 따로 감싸지 않은 이유는 딕셔너리는 이미 찾는 값이 없으면 nil을 잘 반환해주기 때문이다.

[정거장 정보] ViewModel의 Collection 로 선언되어있는 property를 일급 컬렉션으로 추상화한다.

---

BBus/BBus/Foreground/AlarmSetting/View/GetOffTableViewCell.swift
BBus/BBus/Foreground/AlarmSetting/View/GetOnStatusCell.swift
BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift

* cancellables.removeAll() 을 하게되면 각각의 cancellable들의 deinit이 호출되고, 자동으로 .cancel() 이 실행된다고 한다.
[지수님의 PR Comment](https://github.com/boostcampwm-2021/iOS09-BBus/pull/273#discussion_r756572259)

[커스텀 Cell] prepareForReuse 내의 cancellable cancel() 로직 제거

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/Foreground/AlarmSetting/AlarmSettingCoordinator.swift
BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingAPIUseCase.swift
BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift

viewModel에서 isStopLoader를 로직으로 분리하기 애매해 loaderActiveStatus 변수를 두어 그를 바인딩하는 방식으로 변경

[리팩토링] AlarmSetting 화면 UseCase 리팩토링

---

BBus/BBus.xcodeproj/project.pbxproj
BBus/BBus/Foreground/Station/StationCoordinator.swift
BBus/BBus/Foreground/Station/StationViewController.swift
BBus/BBus/Foreground/Station/UseCase/StationAPIUseCase.swift
BBus/BBus/Foreground/Station/UseCase/StationCalculateUseCase.swift
BBus/BBus/Foreground/Station/ViewModel/StationViewModel.swift
BBus/BBus/Global/Network/BBusAPIError.swift

- 타 지역 정거장이라 정보 제공 안되는 얼럿을 띄워야 할 때를 헤더 값이 nil일 때로 판단했었는데 이제 error로 판단하도록 변경함.
- nil로 판단하니 초기 값인지 헤더 정보를 받았는데도 nil이 온 것인지 구분이 불가능해서 변경하였음.
- 따라서 viewModel의 networkError를 그냥 error로 이름 변경하고 거기에 저장한 뒤, 뷰컨에서 $error에 바인딩해서 error를 switch case 문으로 구별해서 알맞은 얼럿을 띄우도록 함.

[리팩토링] Station 화면 UseCase 리팩토링

---

BBus/BBus/Foreground/Home/HomeCoordinator.swift
BBus/BBus/Foreground/Home/HomeViewController.swift
BBus/BBus/Global/Coordinator/AppCoordinator.swift
BBus/BBus/Global/Coordinator/Coordinator.swift

- UIApplication.shared.statusBar는 iOS 13.0 부터 deprecated 되었음 -> 방식 변경 필요!
- StatusBar에 접근하려면 현재 view가 속한 window에 접근해야함
- window를 가지고 있는 것은 AppCoordinator
- 그리고 Home을 start하는 것도 AppCoordinator
- 따라서 AppCoordinator에서 `HomeCoordinator.start(statusBarHeight: CGFloat?)` 로 전달해주도록 하였음.

[리팩토링] 홈 화면 Status Bar 접근 로직 리팩토링

---

BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
BBus/BBus/Foreground/AlarmSetting/View/AlarmSettingView.swift
BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift
BBus/BBus/Foreground/BusRoute/View/BusRouteView.swift
BBus/BBus/Foreground/Home/HomeViewController.swift
BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift
BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift
BBus/BBus/Foreground/Search/SearchViewController.swift
BBus/BBus/Foreground/Station/StationViewController.swift
BBus/BBus/Foreground/Station/View/StationView.swift
BBus/BBus/Global/CustomView/CustomNavigationBar.swift
BBus/BBus/Global/CustomView/RefreshableView.swift

- 모든 뷰 관련 프로퍼티를 [각씬이름]View() 내부로 집어넣음.
- busRouteType을 받아 view의 컬러를 바꾸는 메소드 `configureColor(routeType:)`를 ViewController -> View 쪽으로 이동시킴. 관련 뷰를 ViewController->View로 이동시켰으므로 해당 메소드도 뷰로 이동되어야 한다고 판단.
- Refresh 버튼과 CustomNavigationBar는 추후 프로토콜화 되어 각 뷰컨트롤러에서 구현할 필요없으므로 `addSubview()`는 하지 않아 화면에 보이지 않는 상태임.

[리펙토링] BaseViewController 생성

---

BBus/BBus/Foreground/Home/Model/HomeModel.swift
BBus/BBus/Foreground/Home/UseCase/HomeAPIUseCase.swift
BBus/BBus/Foreground/Home/ViewModel/HomeViewModel.swift

[홈 화면 버그] cancellable이 동시접근되는 이슈
